export const RESET_TRANSACTION_FORM = 'RESET_TRANSACTION_FORM';
export const APPEND_TRANSACTION_FORM = 'APPEND_TRANSACTION_FORM';

export const VALIDATE_TRANSACTION_REQUEST = 'VALIDATE_TRANSACTION_REQUEST';
export const VALIDATE_TRANSACTION_SUCCESS = 'VALIDATE_TRANSACTION_SUCCESS';
export const VALIDATE_TRANSACTION_FAILURE = 'VALIDATE_TRANSACTION_FAILURE';

export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const APPEND_LOGIN_FORM = 'APPEND_LOGIN_FORM';

export const VALIDATE_LOGIN_REQUEST = 'VALIDATE_LOGIN_REQUEST';
export const VALIDATE_LOGIN_SUCCESS = 'VALIDATE_LOGIN_SUCCESS';
export const VALIDATE_LOGIN_FAILURE = 'VALIDATE_LOGIN_FAILURE';
